### ISSUE TITLE
Error After Click "Run Installation"

### ISSUE THREAD

**Issue by flyingBear66** [kodie/bitbar-googlecal#3]
This is the command line after click Run Installation.

It might be I'm doing something wrong but I couldn't understand what is the problem.

cd /Users/ozgunemrezor/Documents/Plugins && npm install home-config googleapis google-auth-library hapi moment open && rm package-lock.json || true && node /Users/ozgunemrezor/Documents/Plugins/googlecal.30m.js getNewToken     
MACBIM055:~ ozgunemrezor$ cd /Users/ozgunemrezor/Documents/Plugins && npm install home-config googleapis google-auth-library hapi moment open && rm package-lock.json || true && node /Users/ozgunemrezor/Documents/Plugins/googlecal.30m.js getNewToken     
npm WARN saveError ENOENT: no such file or directory, open '/Users/ozgunemrezor/Documents/Plugins/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/ozgunemrezor/Documents/Plugins/package.json'
npm WARN Plugins No description
npm WARN Plugins No repository field.
npm WARN Plugins No README data
npm WARN Plugins No license field.

+ moment@2.22.0
+ google-auth-library@1.4.0
+ open@0.0.5
+ home-config@0.1.0
+ googleapis@28.1.0
+ hapi@17.3.1
added 63 packages in 3.748s
TypeError: googleAuth is not a constructor
    at Object.<anonymous> (/Users/ozgunemrezor/Documents/Plugins/googlecal.30m.js:139:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by kodie** [comment]
What version of `node` and `npm` do you have installed on your system?

**Comment by kodie** [comment]
Try running this:

```
cd /Users/ozgunemrezor/Documents/Plugins
npm uninstall googleapis
npm install googleapis@22.2.0
```

and let me know if that fixes it for you. I probably should release an update with fixed dependency versions.

**Comment by shauvik** [comment]
I tried to use this and found that it's actually due to the breaking changes in the google-auth-library:
https://github.com/google/google-auth-library-nodejs/releases/tag/v1.0.0

Changing to this seems to make it proceed.
```
var auth = new googleAuth.GoogleAuth();
var oauth2Client = new googleAuth.OAuth2Client(cfg.clientId, cfg.clientSecret, cfg.clientRedirect);
```

Also, Hapi has changed and server.connection was merged with the constructor.
```
  var server = new Hapi.Server({ port: cfg.serverPort, host: cfg.serverHost });
```

Running the token script manually now fails due to another problem.
```
$ node googlecal.30m.js getNewToken

If your browser did not do so automatically, please visit the following URL:
https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.readonly&response_type=code&client_id=[redacted]&redirect_uri=http%3A%2F%2Flocalhost%3A3000

Debug: internal, implementation, error 
    Error: handler method did not return a value, a promise, or throw an error
    at module.exports.internals.Manager.execute (/Users/shauvik/bitbar-plugins/node_modules/hapi/lib/toolkit.js:52:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
We're all done here! You may now close this window.
An error occured while trying to get your authorization code: reply is not a function
(node:6747) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: reply is not a function
(node:6747) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kodie** [comment]
Thank you @shauvik, I'll get this fixed in the next version release.
